### ISSUE TITLE
Tasks settings sidebar [workflow's editor]

### ISSUE THREAD

**Issue by joseconstela** [tideflow-io/tideflow#70]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24150%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/tideflow-io/tideflow/issues/70)

As a user, I can edit a task settings by clicking on "edit". The settings editor will appear in a new sticky & scrollable sidebar. (instead of being shows in the task's card)

## Current settings editor

<img width="438" alt="Captura de pantalla 2020-04-05 a las 21 30 29" src="https://user-images.githubusercontent.com/6388629/78508112-acfef580-7784-11ea-8b9c-029dde49f998.png">

## Expected settings editor

<img width="762" alt="Captura de pantalla 2020-04-05 a las 21 30 38" src="https://user-images.githubusercontent.com/6388629/78508118-b4be9a00-7784-11ea-9e7a-d2afa1f95e52.png">

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $150.00)

- [<img src='https://avatars2.githubusercontent.com/u/6388629?v=4' alt='joseconstela' width=24 height=24> joseconstela](https://issuehunt.io/u/joseconstela) ($150.00)

### Submitted pull Requests
- [#72 Add sidebar for showing edit form](https://issuehunt.io/r/tideflow-io/tideflow/pull/72)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/tideflow-io/tideflow/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by bobthekingofegypt** [comment]
I thought I'd have a look at this.  Few things I'm not sure about

* Screenshot shows a save button in the sidebar, is that intentional?  How should that save button function compared to the workflow save button?  I added a done button for now that just hides the sidebar.
* What should happen to the edit text link in the card when the side panel is open, I've hidden it for now but not sure how that is for usability.
* when you create a new workflow it defaults to editing the first card, it's hard to understand the link between the sidebar and the currently editing card, especially on a wide monitor where the side bar is quite far away.  Maybe a different background color for currently active card or some other visual link.  Or not start in edit mode.
* handling responsiveness, this wont really work well on mobile, I'm not sure there is a mobile strategy yet but this panel is absolutely positioned with a high z-index so will cover everything.  It would probably need to be modal on mobile in the future.

**Comment by joseconstela** [comment]
Hello @bobthekingofegypt 

Thanks for your points and suggestions! 

- **save button in the sidebar:** The save button on the sidebar is meant to only save the settings for the selected step, not the entire flow. Hiding the sidebar works perfectly for this. So changing the copy to "Done" is perfect as in your PR :) 

One behaviour I've encountered: the settings doesn't seem to get stored if you hide and re-open a task - and the card title doesn't updates.

![Untitled](https://user-images.githubusercontent.com/6388629/80281942-e802a200-870e-11ea-8f7e-25178fceaafd.gif)

- **edit text link in the card** and **defaults to editing the first card** I think both of your points on _not starting in edit mode_ and having a _different background color for currently active card_ are the way to go for usability and ux. 💯

- **handling responsiveness** very valid points! I would consider it mobile-friendly down the road, not just now.

**Comment by joseconstela** [comment]
I've pushed new changes into the master branch that disables the auto editing the first card, and hightlights the task that is in edit-mode.

<img width="546" alt="Captura de pantalla 2020-04-26 a las 22 11 49" src="https://user-images.githubusercontent.com/6388629/80318503-ef0eda80-880a-11ea-9610-72344fffe02f.png">

**Comment by bobthekingofegypt** [comment]
Having never used meteor I was sort expecting it to all be magically reactive I didn't realise the in-progress forms where just hidden.  I've added another changes that replicates that behaviour by having invisible sidebars for each step that track the changes until it is saved.

Highlight color looks nice.

**Comment by joseconstela** [comment]
Thanks @bobthekingofegypt this looks stunning! Yeah you are right. I would have expected the same, but it's Blaze, and me doing front-end stuff 🤣 

I've made one change in top. Let me know what you think :)
